sudo: false
language: node_js
node_js:
  - "8.11"
cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > $HOME/.npmrc
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn --version

before_script:
  # - yarn check # DISABLED because create-react-app requires mismatched versions

script:
  - yarn flow
  - yarn test

before_deploy:
  - yarn build
  - rm .gitignore

deploy:
  provider: script
  script: "yarn deploy" 
  skip_cleanup: true
  on: $TRAVIS_EVENT_TYPE = push
