language: node_js
node_js:
  - "8"

# exclude tags
branches:
  only:
    - master

script: npm run build; cat js/ux-capture.min.js

deploy:
  provider: npm
  email: "web-platform-bot@meetup.com"
  api_key: $NPM_TOKEN
