sudo: false
language: node_js
node_js:
  - "8.11"
cache:
  yarn: true
  directories:
    - node_modules

# exclude tags
branches:
  only:
    - master

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > $HOME/.npmrc
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn --version

before_script:
  - yarn check

script:
  - yarn flow
  - yarn test
  - yarn build

before_deploy:
  - rm .gitignore

# https://github.com/geut/lerna-travis-demo/blob/master/.travis.yml
# deploy:
#   provider: script
#   script: "yarn lerna publish"
#   skip_cleanup: true

# deploy:
#   provider: script
#   script: "yarn do-publish"
#   skip_cleanup: true
  # on:  something only for merges
